spring:
  application:
    name: todoapi

  datasource:
    url: jdbc:h2:mem:todo;MODE=MYSQL

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect